### ISSUE TITLE
Can't write to the redis DB

### ISSUE THREAD

**Issue by talpasco** [strongloop/strong-pubsub-redis#3]
Couldn't find any information on how to write to the redis db using "strong-pubsub-redis"...
I've tried this usage, and it doesn't seems to do anything (and it doesn't fail).
I'm using a local redis installation (windows), and there's nothing in the db after running this example.
(I am able to write to the db using any other way so the connection-string is fine)

```
var Client = require('strong-pubsub');
var Adapter = require('strong-pubsub-redis');
var client = new Client({host: 'localhost', port: 6379}, Adapter);
    client.publish('new topic', 'my message');
```

I guess I'm missing something.
And I was wondering if there's an example of the "strong-pubsub-redis", for a full socket + pub\sub solution.

BTW,
Thank you all for this awesome platform.

Thanks,
Tal

**Comment by JoeKolba** [comment]
I'm experiencing the same problem on Windows as well.  I get a connection but nothing ends up in the database...

**Comment by talpasco** [comment]
I'm actually about to close this issue.
The Redis' PubSub mechanism is actually working as expected, it's not a conventional db, you won't be able to witness it populate a table, but you can see the traffic of the socket connections via Redis-CLI:
https://redis.io/topics/rediscli
